finalsigma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('', include('website.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website import views

app_name = 'website'

urlpatterns = [
  path('', views.index, name='index'),
  path('post/<slug:post_title_slug>/', views.show_post, name='show_post'),
  path('register/', views.register_request, name="register"),
  path('login/', views.login_request, name='login'),
  path('logout/', views.logout_request, name="logout"),
]

website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from datetime import datetime
from storages.backends.gcloud import GoogleCloudStorage
from ckeditor.fields import RichTextField
from martor.models import MartorField

storage = GoogleCloudStorage()

class Post(models.Model):
  title = models.CharField(max_length=100, unique=True)
  body = MartorField()
  slug = models.SlugField(unique=True, blank=True)
  date_created = models.DateTimeField()
  date_modified = models.DateTimeField()
  header_img = models.ImageField(upload_to='header_imgs/')

  def save(self, *args, **kwargs):
    self.slug=slugify(self.title)
    if self.date_created == None:
      self.date_created = datetime.now()
    self.date_modified = datetime.now()
    super(Post, self).save(*args,**kwargs)

  def __str__(self):
    return self.title


class Page(models.Model):
  title = models.CharField(max_length=12, unique=True)
  body = RichTextField()
  external_url = models.URLField()


class UserProfile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.user.username

website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
  email = forms.EmailField(required=True)

  class Meta:
    model = User
    fields = ("username", "email", "password1", "password2")

  def save(self, commit=True):
    user = super(NewUserForm, self).save(commit=False)
    user.email = self.cleaned_data['email']
    if commit:
      user.save()
    return user

website/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from website.models import Post

def index(request):
  context = {}
  posts = Post.objects.all().order_by('-date_created')
  context['posts'] = posts
  for post in context['posts']:
    post.body = post.body[0:150] + "..."
  return render(request, 'website/index.html', context=context)


def show_post(request, post_title_slug):
  context = {}
  try:
    post = Post.objects.get(slug=post_title_slug)
    context['post'] = post
  except Post.DoesNotExist:
    return redirect('/')
  return render(request, 'website/post.html', context=context)


# TODO: Add password-reset feature https://ordinarycoders.com/blog/article/django-password-reset
def register_request(request):
  if request.method == "POST":
    form = NewUserForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      messages.success(request, "Registration successful.")
      return redirect("website:index")
    messages.error(request, "Unsuccessful registration. Invalid information.")
  form = NewUserForm()
  return render(request=request, template_name="website/register.html", context={ "register_form":form })


def login_request(request):
  if request.method == "POST":
    form = AuthenticationForm(request, data=request.POST)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      user = authenticate(username=username, password=password)
      if user is not None:
        login(request, user)
        messages.info(request, f"You are now logged in as {username}.")
        return redirect("website:index")
      else:
        messages.error(request, "Invalid username or password.")
    else:
      messages.error(request, "Invalid username or password.")
  form = AuthenticationForm()
  return render(request=request, template_name="website/login.html", context={"login_form":form})


def logout_request(request):
  logout(request)
  messages.info(request, "You have successfully logged out.")
  return redirect("website:index")

templates/website/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-2QTZQ1BDR7"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-2QTZQ1BDR7');
    </script>
    <!-- Google Adsense -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1600271447697441"
     crossorigin="anonymous"></script>
    <!-- required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'website/style.css' %}">
    <!-- link to bulma css  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <title>Final Sigma | 
      {% block title %}
        Content and Community for Men Who Want to Make It
      {% endblock %}
    </title>
  </head>
  <body>
    {% include "website/includes/navbar.html" %}
    {% include "website/includes/messages.html" %}
    {% block body %}

    {% endblock %}
    <!-- javascript libraries -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- custom javascript -->
    <script src="{% static 'website/js/navbar.js' %}"></script>
  </body>
</html>

templates/website/includes/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/website/includes/navbar.html
<!-- navbar style reference: https://bulma.io/documentation/components/navbar/ -->

{% load static %}

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://finalsigma.io">
      <img src="{% static 'website/img/finalsigma.png' %}"  height="28">
    </a>

    <a rule="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarText">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarText" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="/">
        Home
      </a>
    </div>

    <div class=""navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if user.is_authenticated %}
          <a class="button" href="/logout/">
            Log Out
          </a>
          {% else %}
          <a class="button is-primary" href="/register/">
            <strong>Sign Up</strong>
          </a>
          <a class="button is-light" href="/login/">
            Log In
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  
</nav>

templates/website/index.html
{% extends 'website/base.html' %}
{% load martortags %}

{% block body %}
  <section class="section">
    <div class="container">
      <h1 class="title is-1">Final Sigma</h1>
    </div>
  </section>
  <section class="section">
    <div class="container">
      {% for post in posts %}
      <a href="{% url 'website:show_post' post.slug %}">
        <h2 class="title is-2">{{ post.title }}</h2>
      </a>
      <div class="content">
        {{ post.body|safe_markdown }}(<a href="{% url 'website:show_post' post.slug %}">read more</a>)
      </div><br />
      {% endfor %}
    </div>
  </section>
{% endblock %}

templates/website/login.html
{% extends 'website/base.html' %}

{% block body %}
{% load crispy_forms_tags %}
    
  <div class="container py-5">
    <h1 class="title is-1">Register</h1>
    <form method="POST">
      {% csrf_token %}
      {{ login_form|crispy }}
      <button class="button is-primary" type="submit">Login</button>
    </form>
  </div>
{% endblock %}

templates/website/post.html
{% extends 'website/base.html' %}
{% load martortags %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block body %}
<section class="section">
  <div class="container">
    <h1 class="title is-1">{{ post.title }}</h1>
    <figure class="image is-3by1">
      <img style="object-fit:cover" src="{{ post.header_img.url }}" />
    </figure>
    <div class="content">
      {{ post.body|safe_markdown }}
    </div><br />
  </div>
</section>
{% endblock %}

templates/website/register.html
{% extends 'website/base.html' %}

{% block body %}
{% load crispy_forms_tags %}
    
  <div class="container py-5">
    <h1 class="title is-1">Register</h1>
    <form method="POST">
      {% csrf_token %}
      {{ register_form|crispy }}
      <button class="button is-primary" type="submit">Register</button>
    </form>
  </div>
{% endblock %}